# Site settings
title: tangible interaction
subtitle: learning and<br/>teaching<br/>interdisciplinary
email: kammer@htw-dresden.de
description: create code design
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tangibleinteraction.github.io/" # the base hostname & protocol for your site
author:
street_address: Friedrich-List-Platz 1
city: Dresden
state: 
zip_code: 01069
country: Germany
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/tangibleinteraction/tangibleinteraction.github.io/
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
permalink: pretty
